### ISSUE TITLE
Use with existing metafile?

### ISSUE THREAD

**Issue by janpio** [fabiospampinato/banal#2]
This project is amazing, but it's missing a small bit that would make it even better for us:

We have been looking for a way to use https://esbuild.github.io/analyze/ via a CLI so we can store the resulting files on disk, and take automated screenshots of them. It seems this project does that, _but_ it also always generates the metafile first. Would it be possible to add an option that metafile can be provided instead of the file to be processed to create the metafile?

(PS: Small path problems on Windows, I will open an issue for that)

**Comment by janpio** [comment]
Ok, seems that option "just" would need to skip the bundling and then read the provided file for https://github.com/fabiospampinato/banal/blob/c9277c1ead48c890190806d76d378e5ea0fdc258/src/index.ts#L78

**Comment by fabiospampinato** [comment]
Implemented, see this: https://github.com/fabiospampinato/banal/issues/4#issuecomment-1850756549
