### ISSUE TITLE
Define output location

### ISSUE THREAD

**Issue by janpio** [fabiospampinato/banal#7]
Right now the tool can "only" generate to a temp folder and then automatically opens in a browser. For our use case it would be nice if we could provide a path where the file should be created (or copied to), and in that case opening in a browser can also be skipped.

`--outdir` maybe?

**Comment by fabiospampinato** [comment]
> where the file

What file though? You want just the metadata file I think, but presumably something like `--outdir` shouldn't imply that just the metadata file is outputted?

**Comment by janpio** [comment]
I think I meant the actual generated HTML file with the charts here. We have a setup where we want to commit these to a repository and track them over time (and also take screenshots of them via `puppeteer`)

(The metafile I actually want to bring in to skip the build, see https://github.com/fabiospampinato/banal/pull/6)

**Comment by fabiospampinato** [comment]
Would it be ok if a bit of postprocessing is required? Like I think I would have to add multiple flags for all the possible exact things that different people may want. Is it ok if you have to extract the HTML file from the folder and delete the rest?

**Comment by fabiospampinato** [comment]
Implemented, see this: https://github.com/fabiospampinato/banal/issues/4#issuecomment-1850756549
